name: Dispatch Workflow
 
on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Enter your username'
        required: true
        default: 'Apulessian'
      favorite_color:
        description: 'Enter your favorite color'
        required: true
        default: 'Millenium Jade'
 
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      username: ${{ steps.output_inputs.outputs.username }}
      favorite_color: ${{ steps.output_inputs.outputs.favorite_color }}
    steps:
      - name: Output Inputs
        id: output_inputs
        run: |
          echo "username=${{ github.event.inputs.username }}" >> $GITHUB_OUTPUT
          echo "favorite_color=${{ github.event.inputs.favorite_color }}" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    outputs:
      greeting: ${{ steps.generate_greeting.outputs.greeting }}
    steps:
      - name: Generate Greeting
        id: generate_greeting
        run: |
          USERNAME="${{ needs.job1.outputs.username }}"
          FAVORITE_COLOR="${{ needs.job1.outputs.favorite_color }}"
          GREETING="$USERNAME says hello, and favorite color is $FAVORITE_COLOR"
          echo "greeting=$GREETING" >> $GITHUB_OUTPUT
 
  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Echo Greeting
        run: echo "${{ needs.job2.outputs.greeting }}"