name: Dispatch Workflow
 
on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Enter your username'
        required: true
        default: 'JonPoPo'
      favorite_color:
        description: 'Enter your favorite color'
        required: true
        default: 'blue'
 
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Username and Favorite Color
        run: echo "${{ github.event.inputs.username }} says hello, and favorite color is ${{ github.event.inputs.favorite_color }}"

  say_thank_you:
    runs-on: ubuntu-latest
    needs: say_hello
    outputs: 
      thank_you: ${{steps.set-thank_you.outputs.thank_you}}
    steps:
      - name: Say Thank you
        id: set-thank_you
        run: GREETING="Hello, {{needs.say_hello.output.username}}"
             echo "greeting=$GREETING" 

  display-greeting:
    runs-on: ubuntu-latest
    needs: say_thank_you
    steps:
      - name: Display Greeting
        run: echo "${{needs.say_thank_you.outputs.thank_you}}"
          


